<?php
$array['car'][1][]= 'レクサスCT';
$array['car'][1][]= 'レクサスGS';
$array['car'][1][]= 'レクサスGSハイブリッド';
$array['car'][1][]= 'レクサスHS';
$array['car'][1][]= 'レクサスIS';
$array['car'][1][]= 'レクサスISハイブリッド';
$array['car'][1][]= 'レクサスLSハイブリッド';
$array['car'][1][]= 'レクサスNX';
$array['car'][1][]= 'レクサスNXハイブリッド';
$array['car'][1][]= 'レクサスRC F';
$array['car'][1][]= 'レクサスRX';
$array['car'][1][]= 'レクサスRXハイブリッド';
$array['car'][1][]= 'レクサスUXハイブリッド';
$array['car'][35][]= 'BMW(X1)';
$array['car'][37][]= 'VWポロ';
$array['car'][38][]= 'メルセデスベンツBクラス';
$array['car'][38][]= 'メルセデスベンツCクラス';
$array['car'][38][]= 'メルセデスベンツCクラスワゴン';
$array['car'][39][]= 'ポルシェカイエン';
?>