<?php
$_mailData['info']['fromName'] = "レクサス専門店　OS INC";
$_mailData['info']['fromEmail'] = "lexus@os-inc.jp";
$_mailData['info']['toEmail'] = "lexus@os-inc.jp,osinc.staff.lexus@gmail.com,sugamoto@nexti-jp.com,yokozawa@tratto-brain.jp";
$_mailData['info']['subject'] = "【レクサス専門店・株式会社OS】お問合せありがとうございます。";
$_mailData['info']['subjectC'] = "ホームページよりお問合せがありました。";
$_mailData['info']['msg'] = "%name%様

お問合わせいただいた内容は下記の通りです。
後日ご返答させていただきます。

%msgData%


株式会社OS LEXUS専門店
〒587-0002 大阪府堺市美原区黒山652-1
TEL：072-289-8070
営業時間：10:00～19:00
定休日：水曜日/木曜日";
$_mailData['zaiko']['fromName'] = "レクサス専門店　OS INC";
$_mailData['zaiko']['fromEmail'] = "lexus@os-inc.jp";
$_mailData['zaiko']['toEmail'] = "lexus@os-inc.jp,osinc.staff.lexus@gmail.com,sugamoto@nexti-jp.com,yokozawa@tratto-brain.jp";
$_mailData['zaiko']['subject'] = "【レクサス専門店・株式会社OS】在庫車お問合わせありがとうございます";
$_mailData['zaiko']['subjectC'] = "ホームページより在庫車お問合わせがありました。";
$_mailData['zaiko']['msg'] = "%name%様

お問合わせいただいた内容は下記の通りです。
後日ご返答させていただきます。

%msgData%


株式会社OS LEXUS専門店
〒587-0002 大阪府堺市美原区黒山652-1
TEL：072-289-8070
営業時間：10:00～19:00
定休日：水曜日/木曜日";
$_mailData['purchase']['fromName'] = "レクサス専門店　OS INC";
$_mailData['purchase']['fromEmail'] = "lexus@os-inc.jp";
$_mailData['purchase']['toEmail'] = "lexus@os-inc.jp,osinc.staff.lexus@gmail.com,yokozawa@tratto-brain.jp";
$_mailData['purchase']['subject'] = "【レクサス専門店・株式会社OS】買取査定のお申込みありがとうございます";
$_mailData['purchase']['subjectC'] = "買取査定のお申込みがありました";
$_mailData['purchase']['msg'] = "%name%様

買取査定のお申込みありがとうございます。
内容は下記の通りとなります。
後日ご返答させていただきます。

%msgData%

株式会社OS LEXUS専門店
〒587-0002 大阪府堺市美原区黒山652-1
TEL：072-289-8070
営業時間：10:00～19:00
定休日：水曜日/木曜日";
$_mailData['reserve']['fromName'] = "レクサス専門店　OS INC";
$_mailData['reserve']['fromEmail'] = "lexus@os-inc.jp";
$_mailData['reserve']['toEmail'] = "lexus@os-inc.jp,osinc.staff.lexus@gmail.com,yokozawa@tratto-brain.jp";
$_mailData['reserve']['subject'] = "【レクサス専門店・株式会社OS】ご来店予約ありがとうございます";
$_mailData['reserve']['subjectC'] = "ホームページよりご来店予約がありました";
$_mailData['reserve']['msg'] = "%name%様

ご来店予約いただいた内容は下記の通りです。
確認次第、ご返答させていただきます。

%msgData%


株式会社OS LEXUS専門店
〒587-0002 大阪府堺市美原区黒山652-1
TEL：072-289-8070
営業時間：10:00～19:00
定休日：水曜日/木曜日";
?>